name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  ci:
    strategy:
      matrix:
        platform:
          - macos
          - ubuntu
          - windows
    runs-on: ${{ matrix.platform }}-latest
    name: ${{ matrix.platform }}
    steps:

      - uses: actions/checkout@v2

      - run: mkdir artifact

      - id: artifact
        run: echo '::set-output name=directory::artifact/${{ matrix.platform }}'

      - run: mkdir ${{ steps.artifact.outputs.directory }}

      - id: setup-haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: 8.10.7

      - run: cabal configure --jobs

      - run: cabal freeze

      - run: cat cabal.project.freeze

      - run: cp cabal.project.freeze ${{ steps.artifact.outputs.directory }}

      - uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: ${{ matrix.platform }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: ${{ matrix.platform }}-

      - run: cabal build

      - run: cabal check

      - run: cabal sdist --output-dir ${{ steps.artifact.outputs.directory }}

      - uses: actions/upload-artifact@v2
        with:
          name: recurly-${{ github.sha }}
          path: artifact
